- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: true

- name: Install Docker Compose
  apt:
    name: docker-compose
    state: present

- name: Enable Docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Initialize Docker Swarm
  shell: docker swarm init
  ignore_errors: yes
